security.jwt.token.secret-key: my-secret-key

imdb:
  feign:
    url: https://imdb-top-100-movies1.p.rapidapi.com/
    header1: 0a047bdca9msh68f752488405af0p1a011fjsnc172909c62e3
    header2: imdb-top-100-movies1.p.rapidapi.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

